- gc-coffee/build.gradle
- gc-coffee/src/main/resources/application.properties
> 의존성 추가 / DateBase

- README.md
> ReadME_UPDATE

- gc-coffee/src/main/java/edu/example/gccoffee/Entity/Product.java
> Product 엔티티

- README.md
- gc-coffee/src/main/java/edu/example/gccoffee/entity/Product.java
> main 코드 클론

- gc-coffee/src/main/java/edu/example/gccoffee/GcCoffeeApplication.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/Order.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/OrderItem.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/Product.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/ProductRepository.java
- gc-coffee/src/main/resources/application.properties
> Order.Error

- gc-coffee/src/main/java/edu/example/gccoffee/entity/Category.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/Product.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/ProductRepositoryTests.java
> ProductRepository 테스트

- gc-coffee/src/main/java/edu/example/gccoffee/entity/Order.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/OrderItem.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/OrderStatus.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderItemRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderRepository.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderRepositoryTest.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/ProductRepositoryTest.java
> Order Test 코드 추가

- gc-coffee/build.gradle
- gc-coffee/src/main/java/edu/example/gccoffee/config/QueryDslConfig.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderItemRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/ProductRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemSearchImpl.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemsSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderSearchImpl.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/ProductSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/ProductSearchImpl.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderRepositoryTest.java
> QueryDSL 추가 / 초기설정

- gc-coffee/build.gradle
- gc-coffee/src/main/java/edu/example/gccoffee/config/QueryDslConfig.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderItemRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/ProductRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemSearchImpl.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemsSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderSearchImpl.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/ProductSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/ProductSearchImpl.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderRepositoryTest.java
> Order 코드 클론

- gc-coffee/.gitignore
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderItemRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemSearchImpl.java
- gc-coffee/src/main/resources/application.properties
> main code clone

- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderItemDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/Order.java
- gc-coffee/src/main/java/edu/example/gccoffee/exception/OrderException.java
- gc-coffee/src/main/java/edu/example/gccoffee/exception/OrderTaskException.java
- gc-coffee/src/main/java/edu/example/gccoffee/exception/ProductException.java
- gc-coffee/src/main/java/edu/example/gccoffee/service/OrderService.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderRepositoryTest.java
> Order exception 추가/ Order 엔티티 수정

- .idea/workspace.xml
- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderItemDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/OrderItem.java
- gc-coffee/src/main/java/edu/example/gccoffee/exception/ProductException.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/service/OrderService.java
> Order Code clone

- gc-coffee/src/main/java/edu/example/gccoffee/controller/OrderController.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/ProductSearchImpl.java
> Order controller 주문 추가

- gc-coffee/src/main/java/edu/example/gccoffee/entity/OrderItem.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderItemRepositoryTests.java
- gc-coffee/src/test/resources/application.properties
> 주문 목록 통합 테스트 코드 병합 요청

- gc-coffee/src/test/resources/application.properties
> Test DB연결 url 수정

- gc-coffee/src/main/java/edu/example/gccoffee/controller/OrderController.java
- gc-coffee/src/main/java/edu/example/gccoffee/entity/OrderItem.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/ProductSearchImpl.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderItemRepositoryTests.java
- gc-coffee/src/test/resources/application.properties
> Order Service/ Controller / OrderItem Test코드 추가

- gc-coffee/src/main/java/edu/example/gccoffee/controller/OrderController.java
- gc-coffee/src/main/java/edu/example/gccoffee/controller/advice/APIControllerAdvice.java
- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/exception/OrderException.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderItemRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/OrderRepository.java
- gc-coffee/src/main/java/edu/example/gccoffee/service/OrderItemService.java
- gc-coffee/src/main/java/edu/example/gccoffee/service/OrderService.java
APIControllerAdvice 일부 수정
QueryDSL 사용
> 컨트롤러, 서비스 최신화 병합 요청

- gc-coffee/src/main/java/edu/example/gccoffee/GcCoffeeApplication.java
- gc-coffee/src/main/java/edu/example/gccoffee/config/JPAAuditConfig.java
- gc-coffee/src/main/java/edu/example/gccoffee/controller/advice/APIControllerAdvice.java
- gc-coffee/src/test/java/edu/example/gccoffee/controller/OrderControllerTests.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderItemRepositoryTests.java
> 주문 컨트롤러 테스트 병합 요청

- gc-coffee/build.gradle
- gc-coffee/src/main/resources/application.properties
- gc-coffee/src/main/resources/data.sql
- gc-coffee/src/test/resources/application.properties
> DB 환경 분리 병합 요청

- gc-coffee/build.gradle
- gc-coffee/src/main/java/edu/example/gccoffee/GcCoffeeApplication.java
- gc-coffee/src/main/java/edu/example/gccoffee/config/JPAAuditConfig.java
- gc-coffee/src/main/java/edu/example/gccoffee/controller/advice/APIControllerAdvice.java
- gc-coffee/src/main/resources/application.properties
- gc-coffee/src/main/resources/data.sql
- gc-coffee/src/test/java/edu/example/gccoffee/controller/OrderControllerTests.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderItemRepositoryTests.java
- gc-coffee/src/test/resources/application.properties
> React Code Clone

- gc-coffee/coffee_react/package-lock.json
- gc-coffee/coffee_react/package.json
- gc-coffee/coffee_react/src/App.js
- gc-coffee/src/main/resources/data.sql
> DB 초기값 설정 변경

- gc-coffee/src/main/java/edu/example/gccoffee/controller/OrderController.java
- gc-coffee/src/main/java/edu/example/gccoffee/controller/ProductController.java
- gc-coffee/src/main/java/edu/example/gccoffee/exception/OrderException.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemSearch.java
- gc-coffee/src/main/java/edu/example/gccoffee/repository/search/OrderItemSearchImpl.java
- gc-coffee/src/main/java/edu/example/gccoffee/service/OrderItemService.java
- gc-coffee/src/main/resources/templates/orders/order-item-list.html
- gc-coffee/src/main/resources/templates/orders/order-list.html
관리자가 전체 주문(Orders)와 주문목록(OrderItem)을 조회할 수 있는 페이지를 추가한다.
> 관리자 페이지 주문 조회 기능 구현 및 병합 요청

- gc-coffee/src/main/java/edu/example/gccoffee/controller/OrderRestController.java
- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderItemDTO.java
> Swagger order API 문서 작성

- gc-coffee/build.gradle
- gc-coffee/src/main/java/edu/example/gccoffee/config/SwaggerOpenAPIConfig.java
- gc-coffee/src/main/java/edu/example/gccoffee/controller/OrderRestController.java
- gc-coffee/src/main/java/edu/example/gccoffee/controller/ProductRestController.java
- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderItemDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/dto/PageRequestDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/dto/ProductDTO.java
- gc-coffee/src/main/java/edu/example/gccoffee/exception/ProductException.java
> Swagger API문서 작성

- gc-coffee/build.gradle
- gc-coffee/src/main/java/edu/example/gccoffee/dto/OrderDTO.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderItemRepositoryTests.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/OrderRepositoryTest.java
- gc-coffee/src/test/java/edu/example/gccoffee/repository/ProductRepositoryTests.java
- gc-coffee/src/test/resources/application.properties
> Test application.properties date.sql 설정
